set nocompatible               " be iMproved
filetype off                   " required!

let mapleader=" "

" let Vundle manage Vundle
" required!
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()

Plugin 'gmarik/Vundle.vim'

" Themes
Plugin 'mkarmona/colorsbox'
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'altercation/vim-colors-solarized'
" Plugin 'chriskempson/base16-vim'
" Plugin 'chriskempson/vim-tomorrow-theme'

" repos on github
Plugin 'scrooloose/nerdtree'
"Plugin 'tpope/vim-rails'
"Plugin 'tpope/vim-haml'
Plugin 'elzr/vim-json'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-endwise'
Plugin 'vim-ruby/vim-ruby'
Plugin 'xenoterracide/html.vim'
Plugin 'digitaltoad/vim-jade'
Plugin 'moll/vim-node'
Plugin 'scrooloose/syntastic'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'walm/jshint.vim'
Plugin 'godlygeek/tabular'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'mhinz/vim-startify'

" vim-scripts repos
Plugin 'L9'
Plugin 'FuzzyFinder'
Plugin 'Align'
Plugin 'AutoAlign'
Plugin 'SuperTab'
Plugin 'tComment'

" settings
set nocompatible
"set background=dark
set background=light
"silent! colorscheme colorsbox-material
"silent! colorscheme PaperColor
"silent! colorscheme solarized
"silent! colorscheme Tomorrow-Night-Bright
"colorscheme Tomorrow-Night-Eighties
filetype indent plugin on
syntax on

set shell=$SHELL
set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set confirm
set laststatus=2

set shiftwidth=2
set tabstop=2
set autoindent
set backspace=indent,eol,start
set smarttab
set visualbell
set mouse=a
set number

set incsearch

nnoremap <C-L> :nohl<CR><C-L>
set guifont=Source\ Code\ Pro:h12

if has('gui_running')
	set guioptions=egmrt
endif
