set nocompatible               " be iMproved
filetype off                   " required!

" let Vundle manage Vundle
" required! 
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" repos on github
Bundle "kchmck/vim-coffee-script"
Bundle "scrooloose/nerdtree"
Bundle "tpope/vim-rails"
Bundle "tpope/vim-haml"
Bundle "tpope/vim-markdown"
Bundle "tpope/vim-fugitive"
Bundle "tpope/vim-surround"
Bundle "tpope/vim-endwise"
Bundle "vim-ruby/vim-ruby"
Bundle "xenoterracide/html.vim"

" vim-scripts repos
Bundle "L9"
Bundle "FuzzyFinder"
Bundle "Align"
Bundle "AutoAlign"
Bundle "SuperTab"

" settings
set nocompatible
set background=dark 
colorscheme Tomorrow-Night-Eighties
filetype indent plugin on
syntax on

set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set confirm
set laststatus=2

set shiftwidth=2
set tabstop=2
set autoindent
set backspace=indent,eol,start
set smarttab
set visualbell
set mouse=a
set number

set incsearch

nnoremap <C-L> :nohl<CR><C-L>
set guifont=Source\ Code\ Pro:h12

if has("gui_running")
	set guioptions=egmrt
endif
